### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by csae8092** [grocerist/grocerist-app#31]
let's bring some color into our web-app!
* go to something like https://coolors.co/ to find inspiration (and actual color codes) for colors for our seven classes
* each list and detail view for each class should be colored differently, e.g. the colors of the links `<a>` or headings `<h1>` 

you can define colors as variables doing something like this 

```css
:root {
    --document: #9B5F98;
    --document-hover: #9b5f98c2;
    --person: #ad3f58;
    --karyie: #f5db9e;
...
}

a {
    color: var(--document);
    text-decoration: unset;
}

a:hover { 
    color: var(--document-hover)
} 
```
